baseURL = "https://scuttlebutt.report/"
languageCode = 'en-us'
title = 'Scuttlebutt Report'
theme = 'anatole'

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 100

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 200

[[menu.main]]
  name = "Portfolio"
  url = "/portfolio/"
  weight = 300

[params]
  author = "Tomi"
  profilePicture = "images/Tomi_Profile_BW-alpha.png"
  description = "Maritime OSINT investigations"
